import pymysql
from name_yalsooni.crawler_py.ebest.util import Log

from name_yalsooni.crawler_py.ebest.xaquery.job import TrJob


class T1102Job(TrJob):

    def __init__(self):
        super(T1102Job, self).__init__("t1102")

    def request_process(self):
        self.t_query.SetFieldData("t1102InBlock", "shcode", 0, "023410")
        self.xa_query.request_process(self)

    def response_process(self):
        name = self.t_query.GetFieldData("t1102OutBlock", "hname", 0)
        price = self.t_query.GetFieldData("t1102OutBlock", "price", 0)
        Log.write(name, price)

        conn = self.mysql_connector.get_connection()
        curs = conn.cursor()

        sql = "INSERT INTO COL_EB_T1102 ( REQDT , HNAME , PRICE , SIGN , CHANGE_ , DIFF , VOLUME , RECPRICE , AVG , UPLMTPRICE , DNLMTPRICE , JNILVOLUME , VOLUMEDIFF , OPEN , OPENTIME , HIGH , HIGHTIME , LOW , LOWTIME , HIGH52W , HIGH52WDATE , LOW52W , LOW52WDATE , EXHRATIO , PER , PBRX , LISTING , JKRATE , MEMEDAN , OFFERNOCD1 , BIDNOCD1 , OFFERNO1 , BIDNO1 , DVOL1 , SVOL1 , DCHA1 , SCHA1 , DDIFF1 , SDIFF1 , OFFERNOCD2 , BIDNOCD2 , OFFERNO2 , BIDNO2 , DVOL2 , SVOL2 , DCHA2 , SCHA2 , DDIFF2 , SDIFF2 , OFFERNOCD3 , BIDNOCD3 , OFFERNO3 , BIDNO3 , DVOL3 , SVOL3 , DCHA3 , SCHA3 , DDIFF3 , SDIFF3 , OFFERNOCD4 , BIDNOCD4 , OFFERNO4 , BIDNO4 , DVOL4 , SVOL4 , DCHA4 , SCHA4 , DDIFF4 , SDIFF4 , OFFERNOCD5 , BIDNOCD5 , OFFERNO5 , BIDNO5 , DVOL5 , SVOL5 , DCHA5 , SCHA5 , DDIFF5 , SDIFF5 , FWDVL , FTRADMDCHA , FTRADMDDIFF , FWSVL , FTRADMSCHA , FTRADMSDIFF , VOL , SHCODE , VALUE , JVOLUME , HIGHYEAR , HIGHYEARDATE , LOWYEAR , LOWYEARDATE , TARGET , CAPITAL , ABSCNT , PARPRICE , GSMM , SUBPRICE , TOTAL , LISTDATE , NAME , BFSALES , BFOPERATINGINCOME , BFORDINARYINCOME , BFNETINCOME , BFEPS , NAME2 , BFSALES2 , BFOPERATINGINCOME2 , BFORDINARYINCOME2 , BFNETINCOME2 , BFEPS2 , SALERT , OPERT , ORDRT , NETRT , EPSRT , INFO1 , INFO2 , INFO3 , INFO4 , JANGINFO , T_PER , TONGHWA , DVAL1 , SVAL1 , DVAL2 , SVAL2 , DVAL3 , SVAL3 , DVAL4 , SVAL4 , DVAL5 , SVAL5 , DAVG1 , SAVG1 , DAVG2 , SAVG2 , DAVG3 , SAVG3 , DAVG4 , SAVG4 , DAVG5 , SAVG5 , FTRADMDVAL , FTRADMSVAL , FTRADMDVAG , FTRADMSVAG , INFO5 , SPAC_GUBUN , ISSUEPRICE , ALLOC_GUBUN , ALLOC_TEXT , SHTERM_TEXT , SVI_UPLMTPRICE , SVI_DNLMTPRICE , LOW_LQDT_GU , ABNORMAL_RISE_GU , LEND_TEXT ) VALUES ( now(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s )"
        curs.execute(sql, (
                self.t_query.GetFieldData("t1102OutBlock", "hname", 0),
                self.t_query.GetFieldData("t1102OutBlock", "price", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sign", 0),
                self.t_query.GetFieldData("t1102OutBlock", "change", 0),
                self.t_query.GetFieldData("t1102OutBlock", "diff", 0),
                self.t_query.GetFieldData("t1102OutBlock", "volume", 0),
                self.t_query.GetFieldData("t1102OutBlock", "recprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "avg", 0),
                self.t_query.GetFieldData("t1102OutBlock", "uplmtprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dnlmtprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "jnilvolume", 0),
                self.t_query.GetFieldData("t1102OutBlock", "volumediff", 0),
                self.t_query.GetFieldData("t1102OutBlock", "open", 0),
                self.t_query.GetFieldData("t1102OutBlock", "opentime", 0),
                self.t_query.GetFieldData("t1102OutBlock", "high", 0),
                self.t_query.GetFieldData("t1102OutBlock", "hightime", 0),
                self.t_query.GetFieldData("t1102OutBlock", "low", 0),
                self.t_query.GetFieldData("t1102OutBlock", "lowtime", 0),
                self.t_query.GetFieldData("t1102OutBlock", "high52w", 0),
                self.t_query.GetFieldData("t1102OutBlock", "high52wdate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "low52w", 0),
                self.t_query.GetFieldData("t1102OutBlock", "low52wdate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "exhratio", 0),
                self.t_query.GetFieldData("t1102OutBlock", "per", 0),
                self.t_query.GetFieldData("t1102OutBlock", "pbrx", 0),
                self.t_query.GetFieldData("t1102OutBlock", "listing", 0),
                self.t_query.GetFieldData("t1102OutBlock", "jkrate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "memedan", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offernocd1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidnocd1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offerno1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidno1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dvol1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svol1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dcha1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "scha1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ddiff1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sdiff1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offernocd2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidnocd2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offerno2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidno2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dvol2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svol2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dcha2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "scha2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ddiff2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sdiff2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offernocd3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidnocd3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offerno3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidno3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dvol3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svol3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dcha3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "scha3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ddiff3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sdiff3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offernocd4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidnocd4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offerno4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidno4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dvol4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svol4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dcha4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "scha4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ddiff4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sdiff4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offernocd5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidnocd5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "offerno5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bidno5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dvol5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svol5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dcha5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "scha5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ddiff5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sdiff5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "fwdvl", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmdcha", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmddiff", 0),
                self.t_query.GetFieldData("t1102OutBlock", "fwsvl", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmscha", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmsdiff", 0),
                self.t_query.GetFieldData("t1102OutBlock", "vol", 0),
                self.t_query.GetFieldData("t1102OutBlock", "shcode", 0),
                self.t_query.GetFieldData("t1102OutBlock", "value", 0),
                self.t_query.GetFieldData("t1102OutBlock", "jvolume", 0),
                self.t_query.GetFieldData("t1102OutBlock", "highyear", 0),
                self.t_query.GetFieldData("t1102OutBlock", "highyeardate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "lowyear", 0),
                self.t_query.GetFieldData("t1102OutBlock", "lowyeardate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "target", 0),
                self.t_query.GetFieldData("t1102OutBlock", "capital", 0),
                self.t_query.GetFieldData("t1102OutBlock", "abscnt", 0),
                self.t_query.GetFieldData("t1102OutBlock", "parprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "gsmm", 0),
                self.t_query.GetFieldData("t1102OutBlock", "subprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "total", 0),
                self.t_query.GetFieldData("t1102OutBlock", "listdate", 0),
                self.t_query.GetFieldData("t1102OutBlock", "name", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfsales", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfoperatingincome", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfordinaryincome", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfnetincome", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfeps", 0),
                self.t_query.GetFieldData("t1102OutBlock", "name2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfsales2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfoperatingincome2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfordinaryincome2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfnetincome2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "bfeps2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "salert", 0),
                self.t_query.GetFieldData("t1102OutBlock", "opert", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ordrt", 0),
                self.t_query.GetFieldData("t1102OutBlock", "netrt", 0),
                self.t_query.GetFieldData("t1102OutBlock", "epsrt", 0),
                self.t_query.GetFieldData("t1102OutBlock", "info1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "info2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "info3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "info4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "janginfo", 0),
                self.t_query.GetFieldData("t1102OutBlock", "t_per", 0),
                self.t_query.GetFieldData("t1102OutBlock", "tonghwa", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dval1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sval1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dval2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sval2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dval3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sval3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dval4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sval4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "dval5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "sval5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "davg1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "savg1", 0),
                self.t_query.GetFieldData("t1102OutBlock", "davg2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "savg2", 0),
                self.t_query.GetFieldData("t1102OutBlock", "davg3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "savg3", 0),
                self.t_query.GetFieldData("t1102OutBlock", "davg4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "savg4", 0),
                self.t_query.GetFieldData("t1102OutBlock", "davg5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "savg5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmdval", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmsval", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmdvag", 0),
                self.t_query.GetFieldData("t1102OutBlock", "ftradmsvag", 0),
                self.t_query.GetFieldData("t1102OutBlock", "info5", 0),
                self.t_query.GetFieldData("t1102OutBlock", "spac_gubun", 0),
                self.t_query.GetFieldData("t1102OutBlock", "issueprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "alloc_gubun", 0),
                self.t_query.GetFieldData("t1102OutBlock", "alloc_text", 0),
                self.t_query.GetFieldData("t1102OutBlock", "shterm_text", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svi_uplmtprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "svi_dnlmtprice", 0),
                self.t_query.GetFieldData("t1102OutBlock", "low_lqdt_gu", 0),
                self.t_query.GetFieldData("t1102OutBlock", "abnormal_rise_gu", 0),
                self.t_query.GetFieldData("t1102OutBlock", "lend_text", 0))
        )
        conn.commit()
        conn.close()
